# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yoloNpdOCR',
                'doc_host': 'https://rohitMalhotra07.github.io',
                'git_url': 'https://github.com/rohitMalhotra07/yoloNpdOCR',
                'lib_path': 'yoloNpdOCR'},
  'syms': {'yoloNpdOCR.core': {'yoloNpdOCR.core.foo': ('core.html#foo', 'yoloNpdOCR/core.py')}}}
