# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/config.ipynb.

# %% auto 0
__all__ = ['Config']

# %% ../nbs/config.ipynb 3
class Config:
    base_data_path = "../data/np_char_datasets/"

    test_data_path = "../data/eu-license-plates/eu/de/"

    IMG_SIZE = 640  # Input image size.
    BATCH_SIZE = 64  # Batch size
    EPOCHS = 150  # Number of epochs
    DATA_FILE = "../data/yolov5_pytorch/data.yaml"  # Configuration file
    # MODEL_NAME = 'yolov5s' # Model name
    SAVE_PERIOD = -1  # Save model after interval
    LOGGING_PROJECT = "np_char_ocr"  # Clearml project name also directory name in which project will be saved. If clearml name exists then ok else it creates on its own.
    EXPERIMENT_NAME = f"train_run1_{EPOCHS}_epochs"
    SEED = 42
    CFG = "./models/yolov5s.yaml"
    device = 0  # cuda device, i.e. 0 or 0,1,2,3 or cpu

    weights_path = f"../yolov5/{LOGGING_PROJECT}/{EXPERIMENT_NAME}/weights/best.pt"
